ccflags-y += -Idrivers/media/platform/msm/camera_sec
ccflags-y += -Idrivers/media/platform/msm/camera_sec/isp/
ccflags-y += -Idrivers/media/platform/msm/camera_sec/sensor/io
obj-$(CONFIG_MSM_CPP) += msm_cpp.o
