ccflags-y += -Idrivers/media/platform/msm/camera_sec
ccflags-y += -Idrivers/media/platform/msm/camera_sec/sensor/io
obj-$(CONFIG_MSMB_CAMERA) += msm_led_flash.o
obj-$(CONFIG_MSMB_CAMERA) += msm_led_trigger.o
