ccflags-y += -Idrivers/media/platform/msm/camera_sec
ccflags-y += -Idrivers/media/platform/msm/camera_sec/sensor/io
ccflags-y += -Idrivers/media/platform/msm/camera_sec/sensor/cci
obj-$(CONFIG_MSMB_CAMERA) += msm_actuator.o
